#!/bin/sh
############################################################
#        SCRIPT FOR ITALIAN PART OF SPEECH TAGGING
############################################################
# Tenti Marco
# Universita degli Studi di Firenze
# e-mail: tentimarco0@gmail.com
# Gennaio 2014
###########################################################################
# THESE VARIABLES HAVE TO BE SET:
# For Windows, these should be Windows paths with backslashes (which will need
# single-quoting), not Cygwin-style paths, e.home.
# BIN='C:\TreeTagger\bin'
# The script will probably fail if the BIN or LIB directory names contain
# spaces.  You should install the tree tagger in a directory that does not
# contain spaces in its path (i.e. not under "Program Files").
###############################################################################
#DEFAULT VALUE
#BIN=/usr/local/durmtools/TreeTagger/bin
#CMD=/usr/local/durmtools/TreeTagger/cmd'
#LIB=/usr/local/durmtools/TreeTagger/lib
###############################################################################
#CUSTOMIZE VALUE
BIN='$gatehome$custom/pos_tagger_IT/TreeTagger/bin'
CMD='$gatehome$custom/pos_tagger_IT/TreeTagger/cmd'
LIB='$gatehome$custom/pos_tagger_IT/TreeTagger/lib'
###############################################################################
# set your perl compilator
MWL=${CMD}/mwl-lookup.perl

# set your default options for the Tree Tagger
#TAGGEROPTS="-token -lemma -sgml"
TAGGEROPTS="-token"

# set the path for the tagger command
#TAGGERCMD=${BIN}/tree-tagger
TAGGER=${BIN}/tree-tagger

# set the path for the abbrevations file
ABBR_LIST=${LIB}/italian-abbreviations

# set the path for the parameter file
#PARAMETERS=${LIB}/italian.par
PARFILE=${LIB}/italian.par

#cat $* |
# remove empty lines
#grep -v '^$' |
# recognition of MWLs 
# -- disabled for use with GATE tokens
# $MWL -f ${LIB}/spanish-mwls |
# tagging
#$TAGGER $PARFILE -token -lemma -sgml
$TAGGER $PARFILE $MWL -token 


